server:
  port: 9110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: infrastructure-apigateway # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务

      routes:
        - id: service-edu  #需要 匹配的服务的名字  必须是 注册的applicationname
          uri: lb://service-edu  # bl 表示是负载均衡的方式进行访问      如果加入nacos 依赖的话就可以直接用服务名来访问了  不用写 详细的端口地址
          predicates:     #断言
            - Path=/user/**, /*/college/**  #表示 /* 前一级的 可以是以任何词开头   /**后一级或多级的可以以任何词命名

        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/*/cms/**

        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**

        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**

        - id: service-trade
          uri: lb://service-trade
          predicates:
            - Path=/*/trade/**

        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**

        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**

        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/*/statistics/**

        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**